spring:
  application:
    name: petsitter
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:petsitter}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:petsitter}
    password: ${DB_PASSWORD:petsitter}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
  docker:
    compose:
      enabled: false

vaadin:
  launch-browser: true

logging:
  level:
    root: INFO

